### ISSUE TITLE
Hello Service

### ISSUE THREAD

**Issue by AngelOnFira** [Hack-The-Tunnels-8/hack-the-tunnels-veks#2]
## Description:

Checkout: `service/src/infrastructure/api/router.ts` to get started.

Update the root API message to say "Hello World".

## Acceptance Criteria:

When you navigate to `http://localhost:5000/api/v1/` the message returned is "Hello World".

**Comment by elyssagrant** [comment]
!review

**Comment by rose-salt** [comment]
!approve
